import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class RegistrationGenerator {
    private static final String LETTERS = "abcdefghijklmnopqrstuvwxyz";
    private static final Random random = new Random();

    private static String generateRegistrationNumber() {
        StringBuilder registrationNumber = new StringBuilder();

        // Generate 4 random numbers
        for (int i = 0; i < 4; i++) {
            registrationNumber.append(random.nextInt(10));
        }

        // Generate 3 random letters
        for (int i = 0; i < 3; i++) {
            registrationNumber.append(LETTERS.charAt(random.nextInt(LETTERS.length())));
        }

        // Generate another 3 random numbers
        for (int i = 0; i < 3; i++) {
            registrationNumber.append(random.nextInt(10));
        }

        return registrationNumber.toString();
    }

    private static long generateAndMeasureTime(int arraySize) {
  

        String[] registrationNumbers = new String[arraySize];
          long startTime = System.currentTimeMillis();
        


        // Generate registration numbers and store in the array

        for (int i = 0; i < arraySize; i++) {

            registrationNumbers[i] = generateRegistrationNumber();

        }


        
        // Your operations using registrationNumbers go here

        long elapsedTime = System.currentTimeMillis() - startTime;


        return elapsedTime;

    }

    public static void main(String[] args) {
        int[] arraySizes = {20000, 30000, 50000};

        for (int size : arraySizes) {
            long timeTaken = generateAndMeasureTime(size);
            System.out.println("Time taken for array size " + size + ": " + timeTaken + " milliseconds");
        }
    }
}


/*The StringBuilder class is a mutable sequence of characters in Java that can be used to build a string by incrementally appending or modifying the characters in the sequence.
StringBuilder sb = new StringBuilder();

sb.append("Hello, ");  append is also an alternative for '+' operator

sb.append("world!");

String s = sb.toString(); // "Hello, world!"
In this example, we first create a new instance of the StringBuilder class with a default capacity of 16 characters. We then use the append method to add the strings "Hello, " and "world!" to the sequence of characters. Finally, we convert the StringBuilder object to a string using the toString method.
 --------------------------------------------------------------------------------------------------------
 random.nextInt(10) line in the Java code generates a random integer between 0 (inclusive) and 10 (exclusive), meaning that the generated integers are in the range [0, 10)
 random: This is a Random object that has been previously instantiated, as you have seen in the private static final Random random = new Random(); line.
 nextInt: This is a method of the Random class that generates a random integer within the specified range.
 
 The line registrationNumbers.add(generateRegistrationNumber()); adds a new registration number to the registrationNumbers list, generated by the generateRegistrationNumber() method.(add is a methodin ArrayList class.)
 we use list whwn size of array is not sufficient.
 startTime variable is used to measure the elapsed time taken to generate and add registration numbers to the registrationNumbers list.
 elapsedTime variable is used to store the elapsed time after the loop that generates the registration numbers has completed.*/
